### ISSUE TITLE
Game won't run without Discord

### ISSUE THREAD

**Issue by birbgames** [samsface/godot-discord-game-sdk#2]
If Discord is not running, running the game will only open Discord and do nothing else.

For obvious reasons, we need a way to be able to run the game without Discord.

**Comment by ThunderClapLP** [comment]
There seems to be a flag for that in the sdk.
![grafik](https://user-images.githubusercontent.com/59509654/151677567-ba7bc2a7-1f21-40a7-935e-b9eaf466f242.png)

**Comment by samsface** [comment]
I'm now passing NoRequireDiscord by default.

**Comment by birbgames** [comment]
Working as intended now!
